sudo: required
services:
 - docker

before_install:
  - docker build -t mikercampbell/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mikercampbell/react-test npm test -- --coverage

after_success:
  - docker build -t mikercampbell/multi-client ./client 
  - docker build -t mikercampbell/multi-nginx ./nginx
  - docker build -t mikercampbell/multi-server ./server
  - docker build -t mikercampbell/multi-worker ./worker
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
